### PR TITLE
Fixed music files related to GillStudio and Stella's battle BGM

### PR DESCRIPTION
**Pull request by TheBestAstroNOT**

### CODE REVIEW

**Comment by TheBestAstroNOT** [comment]
Fixed all bugs just need some more testing before moving forward

**Comment by TheBestAstroNOT** [comment]
Added hot reload functionality so even if u change the music selections while ingame u dont need to restart the game to see the changes. You just need to go the next battle/ go to another place and come back/ advance to the next day to see the changes as BGME doesnt like restart the music whenever the script is updated.

**Comment by TheBestAstroNOT** [comment]
Added a description and logo 
image
and copied it to the code folder as well so the description should be preserved between mod compilations

**Comment by TheBestAstroNOT** [comment]
Removed hot reloading and added the ryo and bgme repos as a submodule so on compilation of the mod u will always have the latest versions of both the mods

**Comment by MadMax1960** [comment]
From messages in discord and this, are we waiting on another Ryo wise? Or good to merge?

**Comment by TheBestAstroNOT** [comment]
Waiting for randomisation via ryo to be added. But the things in the repo do work. I just switched to enum and disabled randomisation. You could merge if you want to release an update now and we can add randomisation in 1.1.1

**Comment by MadMax1960** [comment]
Sounds good to me

**Pull request merged**
