### PR TITLE
Updated gender references in Cinema Event dialogues

### PR DESCRIPTION
**Pull request by allylavanda**
Event_Cmmu_003_030_C 
	Line#: 95 - Thanks, man. -> Thanks.
Event_Cmmu_003_045_C 
	Line#: 58 - sorry about that, man. -> sorry about that.
	Line#: 88 - You're a special dude -> You're special
	Line#: 112 - Mr. Leader? -> Mrs. Leader
Event_Cmmu_003_600_C 
	Line#: 2 - two guys -> us
Event_Cmmu_003_715_C 
	Line#: 16 - such a trendy fella -> so trendy
Event_Cmmu_003_735_C 
	Line#: 54 - can be a weird dude sometimes -> can be weird sometimes.
Event_Cmmu_003_737_C
	Line#: 14 - can be a weird dude sometimes -> can be weird sometimes.

### CODE REVIEW

**Review by UguuCat — COMMENTED** [review]
Line #112 -Mr. Leader? -> Mrs. Leader

Mrs. is used for married women.  Should be changed to either miss or ms. to properly show that femc is an unmarried woman.

**Comment by allylavanda** [comment]
> Line #112 -Mr. Leader? -> Mrs. Leader
> 
> Mrs. is used for married women. Should be changed to either miss or ms. to properly show that femc is an unmarried woman.

Fixed, thank you!

**Comment by MadMax1960** [comment]
Are these lines voiced? Typically "man" and "dude" are gender neutral in most modern slang. I'd pull those changes out and stick to just pronoun changes.

**Comment by allylavanda** [comment]
> Are these lines voiced? Typically "man" and "dude" are gender neutral in most modern slang. I'd pull those changes out and stick to just pronoun changes.

I'll go over and see if they are voiced but I'm pretty sure they are, I didn't pull every use of man or dude for the reason of them being gender neutral at times but me and others in the discord agreed on these few. I can re-add them if needed.

**Comment by allylavanda** [comment]
Alright, I've re-added them and removed 003_030 since there are no changes needed for it anymore.

**Comment by allylavanda** [comment]
Alright, I've re-added them and removed 003_030 since there are no changes needed for it anymore.

**Pull request merged**
