### PR TITLE
Overworld dialogue for pronouns and more faithful textboxes.

### PR DESCRIPTION
**Pull request by Giowno**
Apart from two different dialogues that say "he" on 4/7 (Stopped looking and didn't try very hard to locate them) Dorm, Yakushima, Kyoto, and the entire overworld have more immersive text. The files I'm putting in are game-ready, I created a folder for them it wasn't there so I uploaded it.

### CODE REVIEW

**Comment by MadMax1960** [comment]
Immersive Text?

**Comment by Giowno** [comment]
Immersive text!

**Comment by Giowno** [comment]
Also didn't even know what you meant by "Immersive text?" thought you were saying that with a grin on your face. Would've just answered the question off the back... lol.

**Comment by Giowno** [comment]
I finished this after like 20 hours put in,  and it was like 9:00 pm... I might as well explain what "faithful textboxes" are since I didn't actually explain much. So for example, the Mitsuru super fan in the hallway after Yakushima. She'll ask you if you have a picture of her. FEMC in P3P will say that line, my textbox will make her say the same thing. +1000 yen in profit.

**Pull request merged**
